# Generated by Django 5.0.6 on 2024-11-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("whois_data", models.JSONField(blank=True, null=True)),
                ("dns_data", models.JSONField(blank=True, null=True)),
                ("traceroute_data", models.JSONField(blank=True, null=True)),
                ("port_scan_data", models.JSONField(blank=True, null=True)),
                ("ssl_cert_data", models.JSONField(blank=True, null=True)),
                ("ai_assessment", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
